### ISSUE TITLE
Problem on invocation

### ISSUE THREAD

**Issue by groteck** [pbogut/deoplete-elm#1]
Hi, first say thanks for this plugin. :1st_place_medal: 

**Error:** I don't know if I have some wrong configuration on my init.vim for `deoplete` but the `elm` competition is only triggered when I start removing characters.

**Deoplete config:**
```viml
" Deoplete
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources = {}
let g:deoplete#sources.elm = ['elm']

" Echodoc
autocmd VimEnter * call echodoc#enable()
```

** Demo:**
![deoplete_error](https://user-images.githubusercontent.com/833030/31587078-47a9d586-b1db-11e7-8f6f-367f2cd3e769.gif)

**Comment by pbogut** [comment]
Hi @groteck, thank you for your report.

Can you, please, check it with current master version? I think the input pattern was broken, can you confirm if this is working correct now?

**Comment by pbogut** [comment]
I'm closing this one due to lack of the response and I'm pretty sure it is fixed now.
If you disagree @groteck feel free to replay here.

**Comment by groteck** [comment]
:+1: Sorry but I didn't have time to replay earlier
